<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SiteSetting extends Model
{
    protected $table = 'site_settings';

    protected $fillable = [
        'storage_mode',
        'upload_api_base',
        'upload_chunk_mb',
        'local_path',
        'local_mode_enabled',
        'ftp_hostname',
        'ftp_port',
        'ftp_user',
        'ftp_pass',
        'ftp_path',
        'ftp_accounts_json',
        'ftp_multi_enabled',
        'ftp_round_robin_enabled',
        'ftp_fallback_enabled',
        'ftp_default_account_index',
        'ftp_mode_enabled',
        'r2_bucket',
        'r2_key',
        'r2_secret',
        'r2_endpoint',
        'r2_accounts_json',
        'r2_multi_enabled',
        'r2_round_robin_enabled',
        'r2_fallback_enabled',
        'r2_default_account_index',
        'r2_mode_enabled',
        'b2_bucket',
        'b2_key',
        'b2_secret',
        'b2_endpoint',
        'b2_accounts_json',
        'b2_multi_enabled',
        'b2_round_robin_enabled',
        'b2_fallback_enabled',
        'b2_default_account_index',
        'b2_mode_enabled',
        'gdrive_client_id',
        'gdrive_client_secret',
        'gdrive_redirect_uri',
        'gdrive_shared_drive_id',
        'gdrive_mode',
        'gdrive_accounts_json',
        'gdrive_multi_enabled',
        'gdrive_round_robin_enabled',
        'gdrive_fallback_enabled',
        'gdrive_default_account_index',
        'gdrive_mode_enabled',
        'ttb_accounts_json',
        'ttb_multi_enabled',
        'ttb_round_robin_enabled',
        'ttb_fallback_enabled',
        'ttb_default_account_index',
        'ttb_mode_enabled',
        'delete_sync_storage',
        'categories_json',
        'embed_domain_whitelist',
        'embed_host_aliases',
        'embed_strict_mode',
        'embed_watermark_rules_json',
        'embed_player_type',
        'embed_vast_url',
        'embed_vmap_url',
        'embed_custom_html',
        'embed_custom_css',
        'embed_custom_js',
        'embed_jw_library_url',
        'embed_jw_plugin_urls',
        'embed_jw_setup_json',
        'embed_hlsjs_config_json',
        'license_key',
        'license_status',
        'license_plan',
        'license_features_json',
        'license_expires_at',
        'license_bound_domain',
        'license_last_check_at',
        'admin_username',
        'admin_password_hash',
        'ffmpeg_preset',
        'ffmpeg_fps',
        'ffmpeg_threads',
        'hls_segment_duration',
        'ffmpeg_scale_pad_enabled',
        'ffmpeg_scale_mode'
    ];

    protected $casts = [
        'upload_chunk_mb' => 'integer',
        'local_mode_enabled' => 'boolean',
        'ftp_port' => 'integer',
        'ftp_multi_enabled' => 'boolean',
        'ftp_round_robin_enabled' => 'boolean',
        'ftp_fallback_enabled' => 'boolean',
        'ftp_default_account_index' => 'integer',
        'ftp_mode_enabled' => 'boolean',
        'r2_multi_enabled' => 'boolean',
        'r2_round_robin_enabled' => 'boolean',
        'r2_fallback_enabled' => 'boolean',
        'r2_default_account_index' => 'integer',
        'r2_mode_enabled' => 'boolean',
        'b2_multi_enabled' => 'boolean',
        'b2_round_robin_enabled' => 'boolean',
        'b2_fallback_enabled' => 'boolean',
        'b2_default_account_index' => 'integer',
        'b2_mode_enabled' => 'boolean',
        'gdrive_multi_enabled' => 'boolean',
        'gdrive_round_robin_enabled' => 'boolean',
        'gdrive_fallback_enabled' => 'boolean',
        'gdrive_default_account_index' => 'integer',
        'gdrive_mode_enabled' => 'boolean',
        'ttb_multi_enabled' => 'boolean',
        'ttb_round_robin_enabled' => 'boolean',
        'ttb_fallback_enabled' => 'boolean',
        'ttb_default_account_index' => 'integer',
        'ttb_mode_enabled' => 'boolean',
        'delete_sync_storage' => 'boolean',
        'embed_strict_mode' => 'boolean',
        'ffmpeg_fps' => 'integer',
        'ffmpeg_threads' => 'integer',
        'hls_segment_duration' => 'integer',
        'ffmpeg_scale_pad_enabled' => 'boolean',
        'ffmpeg_scale_mode' => 'string',
    ];

    public static function getSettings()
    {
        return static::firstOrCreate(['id' => 1]);
    }
}
